version: '3.9'

services:
  app:
    build: .
    image: infq/logsls:latest
    ports:
      - "${EXPOSE_PORT:-8000}:${PORT:-8000}"
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      WORKERS: ${WORKERS:-4}
      MONGO_HOST: ${MONGO_HOST:-mongo}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_USER: ${MONGO_USER:-root}
      MONGO_PWD: ${MONGO_PWD:-root}
      MONGO_DB: ${MONGO_DB:-log_server}
    restart: always
    depends_on:
      - mongo
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:${PORT:-8000}/health || exit 1" ]
      interval: 60s
      timeout: 5s
      start_period: 30s
      retries: 3

  # 使用外部mongo时，可删除下面的配置
  mongo:
    image: mongo:5.0.14
    # ports:
    #   - "${MONGO_EXPOSE_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD:-root}
    volumes:
      - ${MONGO_DATA:-./data/mongo}:/data/db
    restart: always
